platform :ios, '8.0'

source 'https://joaopedroffranco@bitbucket.org/nmizoguchi/gde-ios-cocoapods.git'

target 'Bandejao' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GDE App
  pod 'GDELibraryiOS'

end
